# Introducción

In [1]:
import tensorflow as tf

2024-02-26 18:45:29.066224: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-26 18:45:29.066261: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-26 18:45:29.067649: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-26 18:45:29.074345: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-26 18:45:29.858335: W tensorflow/compiler/tf2

TensorFlow proporciona una variedad de funciones para crear nuevos tensores precargados con valores. Por ejemplo, al invocar range(n), podemos crear un vector de valores espaciados uniformemente, comenzando en 0 (incluido) y terminando en n(no incluido). De forma predeterminada, el tamaño del intervalo es 1. A menos que se especifique lo contrario, los nuevos tensores se almacenan en la memoria principal y se designan para el cálculo basado en CPU.

In [2]:
x = tf.range(12, dtype=tf.float32)

2024-02-26 18:45:47.005282: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


Cada uno de estos valores se llama elemento del tensor. El tensor xcontiene 12 elementos. Podemos inspeccionar el número total de elementos en un tensor mediante la size función.

In [3]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

Podemos acceder a la forma de un tensor (la longitud a lo largo de cada eje) inspeccionando su shapeatributo. Debido a que aquí estamos tratando con un vector, shapecontiene solo un elemento y es idéntico en tamaño.

In [4]:
x.shape

TensorShape([12])

Podemos cambiar la forma de un tensor sin alterar su tamaño o valores, invocando reshape. Por ejemplo, podemos transformar nuestro vector x cuya forma es (12,) en una matriz Xcon forma (3, 4). Este nuevo tensor conserva todos los elementos pero los reconfigura en una matriz. Observe que los elementos de nuestro vector están dispuestos una fila a la vez y por lo tanto .x[3] == X[0, 3]

In [5]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

Tenga en cuenta que especificar cada componente de forma reshapees redundante. Como ya conocemos el tamaño de nuestro tensor, podemos calcular un componente de la forma teniendo en cuenta el resto. Por ejemplo, dado un tensor de tamaño n y forma del objetivo (h, w), lo sabemos w = n / h.
Para inferir automáticamente un componente de la forma, podemos colocar un elemento -1 para el componente de la forma que debe inferirse automáticamente. En nuestro caso, en lugar de llamar a x.reshape(3,4), podríamos haber llamado de manera equivalente a x.reshape(3, 4) como x.reshape(-1, 4) o x.reshape(3, -1)

Los profesionales a menudo necesitan trabajar con tensores inicializados para contener todos los ceros o unos. Podemos construir un tensor con todos los elementos establecidos en 0 y una forma de (2, 3, 4) mediante la zeros función.

In [6]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [7]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

A menudo deseamos muestrear cada elemento de forma aleatoria (e independiente) de una distribución de probabilidad determinada. Por ejemplo, los parámetros de las redes neuronales suelen inicializarse de forma aleatoria. El siguiente fragmento crea un tensor con elementos extraídos de una distribución gaussiana (normal) estándar con media 0 y desviación estándar 1.

In [8]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.5508819 , -0.8880561 ,  1.7165276 , -0.31434473],
       [ 0.21946113,  0.4425539 ,  0.2925976 , -0.1179775 ],
       [-0.14528398,  1.3569018 ,  0.21928519, -0.52540404]],
      dtype=float32)>

Finalmente, podemos construir tensores proporcionando los valores exactos para cada elemento proporcionando listas de Python (posiblemente anidadas) que contengan literales numéricos. Aquí, construimos una matriz con una lista de listas, donde la lista más externa corresponde al eje 0 y la lista interna corresponde al eje 1.

In [9]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

# 1.1 Indexación y Corte 

Al igual que con las listas de Python, podemos acceder a elementos tensoriales mediante indexación (comenzando con 0). Para acceder a un elemento en función de su posición relativa al final de la lista, podemos utilizar la indexación negativa. Finalmente, podemos acceder a rangos completos de índices mediante cortes (por ejemplo, X [start:stop] ), donde el valor devuelto incluye el primer índice ( start) pero no el último ( stop). Finalmente, cuando sólo se especifica un índice (o segmento) para un $$ K^{th} $$
Tensor de orden, se aplica a lo largo del eje 0. Por lo tanto, en el siguiente código, [-1] selecciona la última fila y [1:3]selecciona la segunda y tercera filas.

In [10]:
X[-1], X[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

Tensors en TensorFlow son inmutables y no se pueden asignar. Variables en TensorFlow hay contenedores de estado mutables que admiten asignaciones. Tenga en cuenta que los gradientes en TensorFlow no fluyen hacia atrás a través de Variablelas asignaciones.

Más allá de asignar un valor al conjunto Variable, podemos escribir elementos de a Variable especificando índices.

In [11]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)  # se asigna el valor 9 al elemento fila 1, col 2.
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

Si queremos asignar el mismo valor a varios elementos, aplicamos la indexación en el lado izquierdo de la operación de asignación. Por ejemplo, accede a la primera y segunda filas, donde toma todos los elementos a lo largo del eje 1 (columna). Si bien analizamos la indexación de matrices, esto también funciona para vectores y tensores de más de dos dimensiones.[:2, :]:

In [12]:
X_var = tf.Variable(X)
X_var[:2, :].assign(tf.ones(X_var[:2, :].shape, dtype=tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

# 1.2 Operaciones